### ISSUE TITLE
大大你好，PoeStrings現在不能對導出后在檔案夾裏的dat64檔進行編輯。

### ISSUE THREAD

**Issue by Acer-bdog** [aianlinb/libggpk#2]
PoeStrings以前是打開GGPK裏的.dat64檔直接進行編輯，現在打開GGPK后不能識別budle.bin文件，又不能對導出后在檔案夾裏的dat64檔進行編輯。可以讓PoeStrings識別在檔案夾裏的dat64檔嗎，謝謝大大。

**Comment by aianlinb** [comment]
Will be implemented on https://github.com/aianlinb/LibGGPK2 in the future.
